correction

diff --git a/0x1C-makefiles/100-Makefile b/0x1C-makefiles/100-Makefile
--- a/0x1C-makefiles/100-Makefile
+++ b/0x1C-makefiles/100-Makefile
@@ -19,3 +19,9 @@ oclean:
 fclean: clean oclean
 
 re: fclean all
+
+m.h:
+	@if [ ! -e "m.h" ]; then \
+		echo "Error: Header file m.h is missing"; \
+		exit 1; \
+	fi
